//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class antecedentesPatologicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public antecedentesPatologicos()
        {
            this.historialClinico = new HashSet<historialClinico>();
        }
    
        public System.Guid idAPatologico { get; set; }
        public string patologiaPrevia { get; set; }
        public string enfermedadInfantil { get; set; }
        public string antecedentesTraumatico { get; set; }
        public Nullable<bool> bursitis { get; set; }
        public Nullable<bool> capsulitis { get; set; }
        public Nullable<bool> enfermedadReumatica { get; set; }
        public string tipoEnfermedadReumatica { get; set; }
        public Nullable<bool> ciatica { get; set; }
        public string otros { get; set; }
        public Nullable<bool> distension { get; set; }
        public Nullable<bool> esguince { get; set; }
        public Nullable<bool> tendinitis { get; set; }
        public Nullable<bool> contracturas { get; set; }
        public Nullable<bool> luxacion { get; set; }
        public Nullable<bool> subluxacion { get; set; }
        public Nullable<bool> fisura { get; set; }
        public Nullable<bool> fractura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historialClinico> historialClinico { get; set; }
    }
}
