//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class antecedentesPatologicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public antecedentesPatologicos()
        {
            this.historialClinico = new HashSet<historialClinico>();
        }
    
        public System.Guid idAPatologico { get; set; }
        public string patologiaPrevia { get; set; }
        public string enfermedadInfantil { get; set; }
        public string antecedentesTraumatico { get; set; }
        public bool bursitis { get; set; }
        public bool capsulitis { get; set; }
        public bool enfermedadReumatica { get; set; }
        public string tipoEnfermedadReumatica { get; set; }
        public bool ciatica { get; set; }
        public string otros { get; set; }
        public bool distension { get; set; }
        public bool esguince { get; set; }
        public bool tendinitis { get; set; }
        public bool contracturas { get; set; }
        public bool luxacion { get; set; }
        public bool subluxacion { get; set; }
        public bool fisura { get; set; }
        public bool fractura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historialClinico> historialClinico { get; set; }
    }
}
