//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class antecedentesFamiliares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public antecedentesFamiliares()
        {
            this.historialClinico = new HashSet<historialClinico>();
        }
    
        public System.Guid idAFamiliares { get; set; }
        public bool dismetrias { get; set; }
        public bool escoliosis { get; set; }
        public bool tibiasVaras { get; set; }
        public bool piesPlanos { get; set; }
        public bool piesCavos { get; set; }
        public bool piesValgos { get; set; }
        public bool piesZambos { get; set; }
        public bool hallusValgus { get; set; }
        public bool dedosGarra { get; set; }
        public string otros { get; set; }
        public bool genuVaro { get; set; }
        public bool genuValgo { get; set; }
        public bool metaAductus { get; set; }
        public bool metaVarus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historialClinico> historialClinico { get; set; }
    }
}
