//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class antecedentesFisiologicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public antecedentesFisiologicos()
        {
            this.historialClinico = new HashSet<historialClinico>();
        }
    
        public System.Guid idAFisiologico { get; set; }
        public bool andador { get; set; }
        public bool tacata { get; set; }
        public Nullable<int> inicioDeambulacion { get; set; }
        public string habitosPosturales { get; set; }
        public Nullable<int> cambiosPonderales { get; set; }
        public bool zurdo { get; set; }
        public bool diestro { get; set; }
        public bool ambidiestro { get; set; }
        public string otros { get; set; }
        public bool partoCabeza { get; set; }
        public bool partoNalgas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historialClinico> historialClinico { get; set; }
    }
}
