//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class antecedentesFamiliares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public antecedentesFamiliares()
        {
            this.historialClinico = new HashSet<historialClinico>();
        }
    
        public System.Guid idAFamiliares { get; set; }
        public Nullable<bool> dismetrias { get; set; }
        public Nullable<bool> escoliosis { get; set; }
        public Nullable<bool> tibiasVaras { get; set; }
        public Nullable<bool> piesPlanos { get; set; }
        public Nullable<bool> piesCavos { get; set; }
        public Nullable<bool> piesValgos { get; set; }
        public Nullable<bool> piesZambos { get; set; }
        public Nullable<bool> hallusValgus { get; set; }
        public Nullable<bool> dedosGarra { get; set; }
        public string otros { get; set; }
        public Nullable<bool> genuVaro { get; set; }
        public Nullable<bool> genuValgo { get; set; }
        public Nullable<bool> metaAductus { get; set; }
        public Nullable<bool> metaVarus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historialClinico> historialClinico { get; set; }
    }
}
