//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bipedestacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bipedestacion()
        {
            this.estudioOrtopodologico = new HashSet<estudioOrtopodologico>();
        }
    
        public System.Guid idBipedestacion { get; set; }
        public string visionAnterior { get; set; }
        public string visionPosterior { get; set; }
        public string visionLateral { get; set; }
        public Nullable<bool> basculaEscapular { get; set; }
        public Nullable<bool> basculaPelvica { get; set; }
        public Nullable<double> balculaPelvicaMM { get; set; }
        public Nullable<bool> posicionEscoliotica { get; set; }
        public Nullable<bool> testAdams { get; set; }
        public string testAdamsGiro { get; set; }
        public Nullable<bool> pruebaIsquiotibilaesCortos { get; set; }
        public Nullable<bool> genuFisiologico { get; set; }
        public Nullable<bool> genuValgo { get; set; }
        public Nullable<double> genuValgoDim { get; set; }
        public Nullable<bool> genuVaro { get; set; }
        public Nullable<double> genuVaroDic { get; set; }
        public Nullable<bool> tibiasFisiologicas { get; set; }
        public Nullable<bool> tibiasValgas { get; set; }
        public Nullable<bool> tibiasVaras { get; set; }
        public Nullable<bool> pieRadioInsuficiente { get; set; }
        public string pieRadioInsucienteNotas { get; set; }
        public Nullable<bool> pieSobrecargaMeta { get; set; }
        public string pieSobrecargaMetaNotas { get; set; }
        public Nullable<System.Guid> id_retropie { get; set; }
        public Nullable<System.Guid> id_antepie { get; set; }
    
        public virtual antepie antepie { get; set; }
        public virtual retropie retropie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudioOrtopodologico> estudioOrtopodologico { get; set; }
    }
}
