//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class decubitoSupinoExploracionMorfologica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public decubitoSupinoExploracionMorfologica()
        {
            this.estudioOrtopodologico = new HashSet<estudioOrtopodologico>();
        }
    
        public System.Guid idEMorfologica { get; set; }
        public bool antepieTriangular { get; set; }
        public string otros { get; set; }
        public Nullable<System.Guid> id_formula_metatarsal { get; set; }
        public Nullable<System.Guid> id_formula_digital { get; set; }
        public Nullable<System.Guid> id_formula_podal { get; set; }
    
        public virtual formulaDigital formulaDigital { get; set; }
        public virtual formulaMetatarsal formulaMetatarsal { get; set; }
        public virtual formulaPodal formulaPodal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudioOrtopodologico> estudioOrtopodologico { get; set; }
    }
}
