//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class decubitoSupinoPosicionAnguloAntepie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public decubitoSupinoPosicionAnguloAntepie()
        {
            this.decubitoSupinoExploracionArticular = new HashSet<decubitoSupinoExploracionArticular>();
        }
    
        public System.Guid idPosicionAnguloAntepie { get; set; }
        public bool valgo { get; set; }
        public bool varo { get; set; }
        public bool supinado { get; set; }
        public bool neutro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<decubitoSupinoExploracionArticular> decubitoSupinoExploracionArticular { get; set; }
    }
}
