//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class decubitoSupinoExploracionArticular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public decubitoSupinoExploracionArticular()
        {
            this.estudioOrtopodologico = new HashSet<estudioOrtopodologico>();
        }
    
        public System.Guid idEArticularIzdo { get; set; }
        public System.Guid idEArticularDcho { get; set; }
        public Nullable<double> dismetriaPiesAltosIzdo { get; set; }
        public Nullable<double> dismetriaPiesAltosDcho { get; set; }
        public Nullable<double> dismetriaPiesBajosIzdo { get; set; }
        public Nullable<double> dismetriaPiesBajosDcho { get; set; }
        public Nullable<double> caderaFlexionIzda { get; set; }
        public Nullable<double> caderaFlexionDcha { get; set; }
        public Nullable<double> caderaExtensionIzda { get; set; }
        public Nullable<double> caderaExtensionDcha { get; set; }
        public Nullable<double> caderaHiperextensionIzda { get; set; }
        public Nullable<double> caderaHiperextensionDcha { get; set; }
        public Nullable<double> caderaAbduccionIzda { get; set; }
        public Nullable<double> caderaAbduccionDcha { get; set; }
        public Nullable<double> caderaAduccionIzda { get; set; }
        public Nullable<double> caderaAduccionDcha { get; set; }
        public Nullable<double> caderaRotInternaIzda { get; set; }
        public Nullable<double> caderaRotInternaDcha { get; set; }
        public Nullable<double> caderaRotExternaIzda { get; set; }
        public Nullable<double> caderaRotExternaDcha { get; set; }
        public Nullable<double> rodillaFlexionIzda { get; set; }
        public Nullable<double> rodillaFlexionDcha { get; set; }
        public Nullable<double> rodillaExtensionIzda { get; set; }
        public Nullable<double> rodillaExtensionDcha { get; set; }
        public Nullable<double> rodillaHiperextensionIzda { get; set; }
        public Nullable<double> rodillaHiperextensionDcha { get; set; }
        public Nullable<bool> genuValgoReductibleIzda { get; set; }
        public Nullable<bool> genuValgoReductibleDcha { get; set; }
        public Nullable<bool> genuValgoIrreductibleIzda { get; set; }
        public Nullable<bool> genuValgoIrreductibleDcha { get; set; }
        public Nullable<bool> genuVaroReductibleIzda { get; set; }
        public Nullable<bool> genuVaroReductibleDcha { get; set; }
        public Nullable<bool> genuVaroIrreductibleIzda { get; set; }
        public Nullable<bool> genuVaroIrreductibleDcha { get; set; }
        public Nullable<double> anguloQizda { get; set; }
        public Nullable<double> anguloQdcha { get; set; }
        public Nullable<double> tpaFpIzda { get; set; }
        public Nullable<double> tpaFpDcha { get; set; }
        public Nullable<double> tpaFdIzda { get; set; }
        public Nullable<double> tpaFdDcha { get; set; }
        public Nullable<double> retropieAsaEversionIzda { get; set; }
        public Nullable<double> retropieAsaEversionDcha { get; set; }
        public Nullable<double> retropieAsaInversionIzda { get; set; }
        public Nullable<double> retropieAsaInversionDcha { get; set; }
        public Nullable<double> mediopiePronacionIzda { get; set; }
        public Nullable<double> mediopiePronacionDcha { get; set; }
        public Nullable<double> mediopieSupinacionIzda { get; set; }
        public Nullable<double> mediopieSupinacionDcha { get; set; }
        public Nullable<double> antepie1radioAmtfFpIzda { get; set; }
        public Nullable<double> antepie1radioAmtfFpDcha { get; set; }
        public Nullable<double> antepie1radioAmtfFdIzda { get; set; }
        public Nullable<double> antepie1radioAmtfFdDcha { get; set; }
        public Nullable<double> antepie1radioFalangeFpIzda { get; set; }
        public Nullable<double> antepie1radioFalangeFpDcha { get; set; }
        public Nullable<bool> antepie1radioHallusLimitusIzdo { get; set; }
        public Nullable<bool> antepie1radioHallusLimitusDcho { get; set; }
        public Nullable<bool> antepie1radioHallusRigidusIzdo { get; set; }
        public Nullable<bool> antepie1radioHallusRigidusDcho { get; set; }
        public Nullable<bool> antepie1radioHallusFlexusIzdo { get; set; }
        public Nullable<bool> antepie1radioHallusFlexusDcho { get; set; }
        public Nullable<bool> antepie1radioHallusHiperextensusIzdo { get; set; }
        public Nullable<bool> antepie1radioHallusHiperextensusDcho { get; set; }
        public Nullable<bool> antepie1radioHallusVizdo { get; set; }
        public Nullable<bool> antepie1radioHallusVdcho { get; set; }
        public string antepie1radioOtrosIzdo { get; set; }
        public string antepie1radioOtrosDcho { get; set; }
        public Nullable<double> antepie25radioAmtfFpIzdo { get; set; }
        public Nullable<double> antepie25radioAmtfFpDcho { get; set; }
        public Nullable<double> antepie25radioAmtfFdIzdo { get; set; }
        public Nullable<double> antepie25radioAmtfFdDcho { get; set; }
        public Nullable<double> antepie25radioProximalFpIzdo { get; set; }
        public Nullable<double> antepie25radioProximalFpDcho1 { get; set; }
        public Nullable<double> antepie25radioProximalFdIzdo1 { get; set; }
        public Nullable<double> antepie25radioProximalFdDcho { get; set; }
        public Nullable<double> antepie25radioDistalFpIzdo { get; set; }
        public Nullable<double> antepie25radioDistalFpDcho { get; set; }
        public Nullable<double> antepie25radioDistalFdIzdo { get; set; }
        public Nullable<double> antepie25radioDistalFdDcho { get; set; }
        public Nullable<bool> antepie25radio5metaCortoIzdo { get; set; }
        public Nullable<bool> antepie25radio5metaCortoDcho { get; set; }
        public Nullable<bool> antepie25radio5varoIzdo { get; set; }
        public Nullable<bool> antepie25radio5varoDcho { get; set; }
        public Nullable<bool> antepie25radio5hipermovilIzdo { get; set; }
        public Nullable<bool> antepie25radio5hipermovilDcho { get; set; }
        public Nullable<bool> antepie25radioJuaneteSastreIzdo { get; set; }
        public Nullable<bool> antepie25radioJuaneteSastreDcho { get; set; }
        public string antepie25radioOtrosIzdo { get; set; }
        public string antepie25radioOtrosDcho { get; set; }
        public Nullable<System.Guid> id_posicion_angulo_antepie { get; set; }
        public Nullable<System.Guid> id_posicion_1_radio { get; set; }
    
        public virtual decubitoSupinoAntepiePosicion1Radio decubitoSupinoAntepiePosicion1Radio { get; set; }
        public virtual decubitoSupinoPosicionAnguloAntepie decubitoSupinoPosicionAnguloAntepie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudioOrtopodologico> estudioOrtopodologico { get; set; }
    }
}
