//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnostico
    {
        public System.Guid idDiagnostico { get; set; }
        public string anotaciones { get; set; }
        public Nullable<System.Guid> id_primera_visita { get; set; }
    
        public virtual primeraVisita primeraVisita { get; set; }
    }
}
