//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudioOrtopodologico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estudioOrtopodologico()
        {
            this.primeraVisita = new HashSet<primeraVisita>();
        }
    
        public System.Guid idEOrtopodologico { get; set; }
        public Nullable<System.Guid> id_dse_articular_izdo { get; set; }
        public Nullable<System.Guid> id_dse_articular_dcho { get; set; }
        public Nullable<System.Guid> id_dse_muscular_dcho { get; set; }
        public Nullable<System.Guid> id_dse_muscular_izdo { get; set; }
        public Nullable<System.Guid> id_dse_morfologico { get; set; }
        public Nullable<System.Guid> id_dp_articular_dcho { get; set; }
        public Nullable<System.Guid> id_dp_articular_izdo { get; set; }
        public Nullable<System.Guid> id_se_articular_dcho { get; set; }
        public Nullable<System.Guid> id_se_articular_izdo { get; set; }
        public Nullable<System.Guid> id_se_muscular_dcho { get; set; }
        public Nullable<System.Guid> id_se_muscular_izdo { get; set; }
        public Nullable<System.Guid> id_adv_frontal { get; set; }
        public Nullable<System.Guid> id_adv_sagital { get; set; }
        public Nullable<System.Guid> id_deambulacion { get; set; }
        public Nullable<System.Guid> id_bipedestacion { get; set; }
        public Nullable<System.Guid> id_pulsos { get; set; }
    
        public virtual bipedestacion bipedestacion { get; set; }
        public virtual deambulacion deambulacion { get; set; }
        public virtual decubitoPronoExploracionArticular decubitoPronoExploracionArticular { get; set; }
        public virtual decubitoSupinoExploracionArticular decubitoSupinoExploracionArticular { get; set; }
        public virtual decubitoSupinoExploracionMorfologica decubitoSupinoExploracionMorfologica { get; set; }
        public virtual decubitoSupinoExploracionMuscular decubitoSupinoExploracionMuscular { get; set; }
        public virtual decubitoSupinoPulsos decubitoSupinoPulsos { get; set; }
        public virtual sedestacionExploracionArticular sedestacionExploracionArticular { get; set; }
        public virtual sedestacionExploracionMuscular sedestacionExploracionMuscular { get; set; }
        public virtual visionFrontal visionFrontal { get; set; }
        public virtual visionSagital visionSagital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<primeraVisita> primeraVisita { get; set; }
    }
}
