//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FPI()
        {
            this.bipedestacion = new HashSet<bipedestacion>();
        }
    
        public System.Guid idFPI { get; set; }
        public Nullable<int> palpacionEstragaloIzda { get; set; }
        public Nullable<int> palpacionEstragaloDcha { get; set; }
        public Nullable<int> curvaturaMaleolarIzda { get; set; }
        public Nullable<int> curvaturaMaleolarDcha { get; set; }
        public Nullable<int> posicionCalcaneoIzda { get; set; }
        public Nullable<int> posicionCalcaneoDcha { get; set; }
        public Nullable<int> prominenciaArticulacionIzda { get; set; }
        public Nullable<int> prominenciaArticulacionDcha { get; set; }
        public Nullable<int> alturaYcongruenciaIzda { get; set; }
        public Nullable<int> alturaYcongruenciaDcha { get; set; }
        public Nullable<int> abduccionYaduccionIzda { get; set; }
        public Nullable<int> abduccionYaduccionDcha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bipedestacion> bipedestacion { get; set; }
    }
}
