//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialSoportePlantar
    {
        public System.Guid idMaterialSoportePlantar { get; set; }
        public bool TAD { get; set; }
        public bool resinas { get; set; }
        public bool EVA { get; set; }
        public bool propileno { get; set; }
        public string componentes { get; set; }
        public string otros { get; set; }
        public Nullable<System.Guid> id_tratamiento { get; set; }
    
        public virtual tratamiento tratamiento { get; set; }
    }
}
