//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pruebasComplementarias
    {
        public System.Guid idPrueba { get; set; }
        public byte[] pedigrafia { get; set; }
        public byte[] rayosX { get; set; }
        public byte[] analisisSanguineo { get; set; }
        public byte[] cultivo { get; set; }
        public byte[] doppler { get; set; }
        public byte[] ecografia { get; set; }
        public byte[] fotos { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.Guid> id_primera_visita { get; set; }
    
        public virtual primeraVisita primeraVisita { get; set; }
    }
}
