//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sedestacionExploracionArticular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sedestacionExploracionArticular()
        {
            this.estudioOrtopodologico = new HashSet<estudioOrtopodologico>();
        }
    
        public System.Guid idEArticularPieIzdo { get; set; }
        public System.Guid idEArticularPieDcho { get; set; }
        public Nullable<double> anteversionFemoralNinosIzda { get; set; }
        public Nullable<double> anteversionFemoralNinosDcha { get; set; }
        public Nullable<double> anteversionFemoralAdultosIzda { get; set; }
        public Nullable<double> anteversionFemoralAdultosDcha { get; set; }
        public Nullable<double> anguloTorsionBimaleolarIzda { get; set; }
        public Nullable<double> anguloTorsionBimaleolarDcha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudioOrtopodologico> estudioOrtopodologico { get; set; }
    }
}
