//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tratamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tratamiento()
        {
            this.materialSoportePlantar = new HashSet<materialSoportePlantar>();
        }
    
        public System.Guid idTratamiento { get; set; }
        public bool fisico { get; set; }
        public string ejerciciosPropioceptivos { get; set; }
        public bool farmacologico { get; set; }
        public bool quiropodologico { get; set; }
        public bool ortosisDigital { get; set; }
        public string ortosisDigitalTipo { get; set; }
        public bool soportePlantar { get; set; }
        public bool vendajeFuncional { get; set; }
        public bool preventivo { get; set; }
        public string preventivoObservacion { get; set; }
        public bool calzadoterapia { get; set; }
        public string otros { get; set; }
        public Nullable<System.Guid> id_primera_visita { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialSoportePlantar> materialSoportePlantar { get; set; }
        public virtual primeraVisita primeraVisita { get; set; }
    }
}
